services:
  - type: web
    name: bbb-backend
    env: node
    rootDir: backend
    buildCommand: npm install && npm run build && npx prisma db push --skip-generate
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: HANDOVER_TOKEN_SECRET
        generateValue: true
      - key: CLIENT_URL
        sync: false
      - key: COOKIE_SAME_SITE
        value: none
